### ISSUE TITLE
创建heroku时仍然报错，提示：configure.sh: no such file or directory

### ISSUE THREAD

**Issue by Fallen-ending** [Dimitri2020007/vless-heroku#2]
已经fork项目并修改用户名，但是第九步还是报错，部分日志如下：
Step 8/11 : COPY etc/Caddyfile /conf/Caddyfile
 ---> 1653ecc2d99a
Step 9/11 : ADD configure.sh /configure.sh
ADD failed: stat /var/lib/docker/tmp/docker-builder524945648/configure.sh: no such file or directory

**Comment by Dimitri2020007** [comment]
我已经修复这个问题，请删除本项目后重新fork即可。
